version: "3.11"

services:
  web:
    build:
      context: ./webapp
    container_name: django_web
    command: bash entrypoint.sh
    volumes:
      - ./webapp:/code
    ports:
      - "8080:8000"
    env_file:
      - ./webapp/.env.docker

  api:
    build:
      context: ./video-classifier
      dockerfile: Dockerfile
    container_name: video_classifier
    volumes:
      - ./video-classifier:/code
    ports:
      - "8001:8000"