version: "3.9"

services:
  web:
    build:
      context: ./Webapp
    container_name: django_web
    command: bash entrypoint.sh
    volumes:
      - ./Webapp:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: ./Webapp
    container_name: celery_worker
    command: celery -A webapp worker --loglevel=info
    volumes:
      - ./Webapp:/code
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
