version: "3.9"

services:
  web:
    build:
      context: ./webapp
    container_name: django_web
    command: bash entrypoint.sh
    volumes:
      - ./webapp:/code
    ports:
      - "8080:8000"
    # env_file:
    #   - .env
    # depends_on:
    #   - redis

  api:
    build:
      context: ./video-classifier
      dockerfile: Dockerfile
    container_name: video_classifier
    volumes:
      - ./video-classifier:/code
    ports:
      - "8001:8000"
    # env_file:
    #   - .env
    # depends_on:
    #   - redis

  # worker:
  #   build:
  #     context: ./Webapp
  #   container_name: celery_worker
  #   command: celery -A webapp worker --loglevel=info
  #   volumes:
  #     - ./Webapp:/code
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis

  # redis:
  #   image: redis:7
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
