# Generated by Django 4.2.20 on 2025-04-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_doorframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='WalkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pee', 'Pee'), ('poo', 'Poo'), ('both', 'Both'), ('play', 'Play'), ('other', 'Other')], max_length=50)),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='walks.walk')),
            ],
        ),
    ]
