# Generated by Django 4.2.20 on 2025-04-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WalkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pee', 'Pee'), ('poo', 'Poo'), ('diarrhea', 'Diarrhea'), ('vomit', 'Vomit'), ('other', 'Other')], max_length=50)),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='walks.walk')),
            ],
        ),
    ]
