# Generated by Django 4.2.20 on 2025-04-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0002_walk_status_alter_walk_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkevent',
            name='event_type',
            field=models.CharField(choices=[('pee', 'Pee'), ('poo', 'Poo'), ('both', 'Both'), ('play', 'Play'), ('other', 'Other')], max_length=50),
        ),
    ]
