FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV DJANGO_SUPERUSER_USERNAME=jensen
ENV DJANGO_SUPERUSER_EMAIL=seanmarcusj@gmail.com
ENV DJANGO_SUPERUSER_PASSWORD=cw41

RUN python manage.py createsuperuser --noinput || true

CMD ["gunicorn", "webapp.wsgi:application", "--bind", "0.0.0.0:8000"]
